language: python

python:
  - "2.7"

# command to install requirements
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run --source=. manage.py test

after_success:
  - coveralls
